/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-03 00:28:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class date_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1606304214663L));
    _jspx_dependants.put("jar:file:/D:/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>Calendar</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".cal_top{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("}\r\n");
      out.write(".cal{\r\n");
      out.write("    text-align: center;    \r\n");
      out.write("}\r\n");
      out.write("table.calendar{\r\n");
      out.write("    border: 1px solid black;\r\n");
      out.write("    display: inline-table;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("table.calendar td{\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    border: 1px solid skyblue;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"cal_top\">\r\n");
      out.write("        <a href=\"#\" id=\"movePrevMonth\"><span id=\"prevMonth\" class=\"cal_tit\">&lt;</span></a>\r\n");
      out.write("        <span id=\"cal_top_year\"></span>\r\n");
      out.write("        <span id=\"cal_top_month\"></span>\r\n");
      out.write("        <a href=\"#\" id=\"moveNextMonth\"><span id=\"nextMonth\" class=\"cal_tit\">&gt;</span></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"cal_tab\" class=\"cal\">\r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    var today = null;\r\n");
      out.write("    var year = null;\r\n");
      out.write("    var month = null;\r\n");
      out.write("    var firstDay = null;\r\n");
      out.write("    var lastDay = null;\r\n");
      out.write("    var $tdDay = null;\r\n");
      out.write("    var $tdSche = null;\r\n");
      out.write(" \r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        drawCalendar();\r\n");
      out.write("        initDate();\r\n");
      out.write("        drawDays();\r\n");
      out.write("        getlist();\r\n");
      out.write("        $(\"#movePrevMonth\").on(\"click\", function(){movePrevMonth();});\r\n");
      out.write("        $(\"#moveNextMonth\").on(\"click\", function(){moveNextMonth();});\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    function getlist(){\r\n");
      out.write("    \t  let row = $(\"#cal_tab .calendar td\");\r\n");
      out.write("          let strYear = $(\"#cal_top_year\").html();\r\n");
      out.write("          let year = strYear.substring(2);\r\n");
      out.write("          let month = $(\"#cal_top_month\").html();\r\n");
      out.write("          for(var i = 1; i <= 31; i++) {\r\n");
      out.write("             let day = i;\r\n");
      out.write("             if(day >= 1 && day <= 9) {\r\n");
      out.write("                day = \"0\" + i;\r\n");
      out.write("             }\r\n");
      out.write("             let date = year + \"/\" + month +\"/\"+ day;\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          $.ajax({\r\n");
      out.write("             type : \"get\",\r\n");
      out.write("             url : \"datecal.json\",\r\n");
      out.write("             dataType : \"json\",\r\n");
      out.write("             data : {\"day\" : date},\r\n");
      out.write("             success : function(data) {\r\n");
      out.write("                $(data).each(function() {\r\n");
      out.write("                   let showDay = this.day.substring(0,11);\r\n");
      out.write("                   if(date.equals(showDay)) {\r\n");
      out.write("                      row.find(\".cal-schedule\").html(showday);\r\n");
      out.write("                   }\r\n");
      out.write("                });\r\n");
      out.write("             }\r\n");
      out.write("          });\r\n");
      out.write("          }\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    //calendar 그리기\r\n");
      out.write("    function drawCalendar(){\r\n");
      out.write("        var setTableHTML = \"\";\r\n");
      out.write("        setTableHTML+='<table class=\"calendar\">';\r\n");
      out.write("        setTableHTML+='<tr><th>SUN</th><th>MON</th><th>TUE</th><th>WED</th><th>THU</th><th>FRI</th><th>SAT</th></tr>';\r\n");
      out.write("        for(var i=0;i<6;i++){\r\n");
      out.write("            setTableHTML+='<tr height=\"100\">';\r\n");
      out.write("            for(var j=0;j<7;j++){\r\n");
      out.write("                setTableHTML+='<td style=\"text-overflow:ellipsis;overflow:hidden;white-space:nowrap\">';\r\n");
      out.write("                setTableHTML+='    <div class=\"cal-day\"></div>';\r\n");
      out.write("                setTableHTML+='    <div class=\"cal-schedule\"></div>';\r\n");
      out.write("                setTableHTML+='</td>';\r\n");
      out.write("            }\r\n");
      out.write("            setTableHTML+='</tr>';\r\n");
      out.write("        }\r\n");
      out.write("        setTableHTML+='</table>';\r\n");
      out.write("        $(\"#cal_tab\").html(setTableHTML);\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    //날짜 초기화\r\n");
      out.write("    function initDate(){\r\n");
      out.write("        $tdDay = $(\"td div.cal-day\")\r\n");
      out.write("        $tdSche = $(\"td div.cal-schedule\")\r\n");
      out.write("        dayCount = 0;\r\n");
      out.write("        today = new Date();\r\n");
      out.write("        year = today.getFullYear();\r\n");
      out.write("        month = today.getMonth()+1;\r\n");
      out.write("        firstDay = new Date(year,month-1,1);\r\n");
      out.write("        lastDay = new Date(year,month,0);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //calendar 날짜표시\r\n");
      out.write("    function drawDays(){\r\n");
      out.write("        $(\"#cal_top_year\").text(year);\r\n");
      out.write("        $(\"#cal_top_month\").text(month);\r\n");
      out.write("        for(var i=firstDay.getDay();i<firstDay.getDay()+lastDay.getDate();i++){\r\n");
      out.write("            $tdDay.eq(i).text(++dayCount);\r\n");
      out.write("        }\r\n");
      out.write("        for(var i=0;i<42;i+=7){\r\n");
      out.write("            $tdDay.eq(i).css(\"color\",\"red\");\r\n");
      out.write("        }\r\n");
      out.write("        for(var i=6;i<42;i+=7){\r\n");
      out.write("            $tdDay.eq(i).css(\"color\",\"blue\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    //calendar 월 이동\r\n");
      out.write("    function movePrevMonth(){\r\n");
      out.write("        month--;\r\n");
      out.write("        if(month<=0){\r\n");
      out.write("            month=12;\r\n");
      out.write("            year--;\r\n");
      out.write("        }\r\n");
      out.write("        if(month<10){\r\n");
      out.write("            month=String(\"0\"+month);\r\n");
      out.write("        }\r\n");
      out.write("        getNewInfo();\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("    function moveNextMonth(){\r\n");
      out.write("        month++;\r\n");
      out.write("        if(month>12){\r\n");
      out.write("            month=1;\r\n");
      out.write("            year++;\r\n");
      out.write("        }\r\n");
      out.write("        if(month<10){\r\n");
      out.write("            month=String(\"0\"+month);\r\n");
      out.write("        }\r\n");
      out.write("        getNewInfo();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    function getNewInfo(){\r\n");
      out.write("        for(var i=0;i<42;i++){\r\n");
      out.write("            $tdDay.eq(i).text(\"\");\r\n");
      out.write("        }\r\n");
      out.write("        dayCount=0;\r\n");
      out.write("        firstDay = new Date(year,month-1,1);\r\n");
      out.write("        lastDay = new Date(year,month,0);\r\n");
      out.write("        drawDays();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
